### PR TITLE
feat: Remote implementation method in example commented #1

### PR DESCRIPTION
**Pull request by kattsushi**

### CODE REVIEW

**Comment by kattsushi** [comment]
I suggest the following like that
declare var module: any;

because it creates a type error when trying to export the module

declare var module: { exports: <%= modelName %> };

**Comment by jonathan-casarrubias** [comment]
Hi @kattsushi thanks for your contribution. But, let me think and experiment about this, because I want to avoid a huge constructor, in this example from the config to the method are all within the constructor which I believe could lead to issues.

I'll try to decouple and see if we can move the config out of the TS File.

Also the method should be outside the constructor and should be static.

Anyway, I'll review and share what I find.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Hi @kattsushi 

I spent some time on this today, I came up with a different solution that is more decoupled.

For now I will need to cancel this pull request, but helped for inspiration on this feature.

Cheers
Jon

**Comment by kattsushi** [comment]
quiet jonathan anything :) the truth is that it was not clear but that was the tip to the idea anyway you have all the reason so maybe some problems if it occupies a builder and not a static method, I'll be testing and I let you know in any case,
you're welcome!

**Pull request closed without merging**
